CREATE TABLE "public"."mec_passagem"
(
 "id_passagem"     integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 "data_inclusao"   timestamp NULL,
 "data_alteracao"  timestamp NULL,
 "id_prontuario"   integer NULL,
 "cd_passagem_wpd" varchar(10) NULL,
 "data_entrada"    timestamp NULL,
 "hora_entrada"    timestamp NULL,
 "data_saida"      timestamp NULL,
 "hora_saida"      timestamp NULL,
 "tipo_paciente"   varchar(50) NULL,
 "especialidade"   varchar(100) NULL,
 CONSTRAINT "idx_id_prontuario" FOREIGN KEY ( "id_prontuario" ) REFERENCES "public"."mec_prontuario" ( "id_prontuario" ) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE UNIQUE INDEX "PK_id_passagem" ON "public"."mec_passagem"
(
 "id_passagem"
);

CREATE INDEX "FK_id_prontuario" ON "public"."mec_passagem"
(
 "id_prontuario"
);

CREATE INDEX "idx_cd_passagem_wpd" ON "public"."mec_passagem"
(
 "cd_passagem_wpd"
);













-- *************** SqlDBM: PostgreSQL ****************;
-- ***************************************************;


-- ************************************** "public"."mec_unidade_saude"

CREATE TABLE "public"."mec_unidade_saude"
(
 "id_unidade_saude"  integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 "data_inclusao"     timestamp NULL,
 "data_alteracao"    timestamp NULL,
 "unidade_saude"     varchar(50) NULL,
 "tipo_unidade"      varchar(50) NULL,
 "rua_unidade_saude" varchar(80) NULL,
 "cep_unidade_saude" varchar(20) NULL

);

CREATE UNIQUE INDEX "PK_id_unidade_saude" ON "public"."mec_unidade_saude"
(
 "id_unidade_saude"
);





















-- *************** SqlDBM: PostgreSQL ****************;
-- ***************************************************;


-- ************************************** "public"."mec_unidade_saude_end"

CREATE TABLE "public"."mec_unidade_saude_end"
(
 "id_unidade_saude_end" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 "data_inclusao"        timestamp NULL,
 "data_alteracao"       timestamp NULL,
 "id_unidade_saude"     integer NULL,
 "unidade_saude"        varchar(50) NULL,
 "rua"                  varchar(80) NULL,
 "cep"                  varchar(20) NULL,
 "numero"               varchar(50) NULL,
 "complemento"          varchar(100) NULL,
 "bairro"               varchar(100) NULL,
 "cidade"               varchar(50) NULL,
 "uf"                   varchar(20) NULL,
 CONSTRAINT "idx_id_unidade_saude" FOREIGN KEY ( "id_unidade_saude" ) REFERENCES "public"."mec_unidade_saude" ( "id_unidade_saude" ) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE UNIQUE INDEX "PK_ id_unidade_saude_end" ON "public"."mec_unidade_saude_end"
(
 "id_unidade_saude_end"
);

CREATE INDEX "FK_id_unidade_saude" ON "public"."mec_unidade_saude_end"
(
 "id_unidade_saude"
);

CREATE INDEX "idx_cep" ON "public"."mec_unidade_saude_end"
(
 "cep"
);




















-- *************** SqlDBM: PostgreSQL ****************;
-- ***************************************************;


-- ************************************** "public"."mec_prontuario"

CREATE TABLE "public"."mec_prontuario"
(
 "id_prontuario"        integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 "data_inclusao"        timestamp NULL,
 "data_alteracao"       timestamp NULL,
 "id_unidade_saude_end" integer NULL,
 "id_procedencia"       integer NULL,
 "cd_prontuario_wpd"    varchar(10) NULL,
 "paciente"             varchar(100) NULL,
 "sexo"                 varchar(15) NULL,
 "dt_nascimento"        timestamp NULL,
 "celular"              varchar(20) NULL,
 "email_paciente"       varchar(100) NULL,
 "nome_responsavel"     varchar(100) NULL,
 "fone_responsavel"     varchar(20) NULL,
 "rua"                  varchar(80) NULL,
 "numero_casa"          varchar(50) NULL,
 "complemento"          varchar(100) NULL,
 "bairro"               varchar(100) NULL,
 "cidade"               varchar(50) NULL,
 "uf_estado"            varchar(20) NULL,
 "cep"                  varchar(20) NULL,
 CONSTRAINT "idx_id_unidade_saude" FOREIGN KEY ( "id_unidade_saude_end" ) REFERENCES "public"."mec_unidade_saude_end" ( "id_unidade_saude_end" ) ON DELETE RESTRICT ON UPDATE RESTRICT,
 CONSTRAINT "idx_id_procedencia" FOREIGN KEY ( "id_procedencia" ) REFERENCES "public"."mec_procedencia" ( "id_procedencia" ) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE UNIQUE INDEX "PK_id_prontuario" ON "public"."mec_prontuario"
(
 "id_prontuario"
);

CREATE INDEX "FK_ id_unidade_saude_end" ON "public"."mec_prontuario"
(
 "id_unidade_saude_end"
);

CREATE INDEX "FK_id_procedencia" ON "public"."mec_prontuario"
(
 "id_procedencia"
);

CREATE INDEX "idx_cd_prontuario_wpd" ON "public"."mec_prontuario"
(
 "cd_prontuario_wpd"
);




















-- *************** SqlDBM: PostgreSQL ****************;
-- ***************************************************;


-- ************************************** "public"."mec_passagem"

CREATE TABLE "public"."mec_passagem"
(
 "id_passagem"     integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 "data_inclusao"   timestamp NULL,
 "data_alteracao"  timestamp NULL,
 "id_prontuario"   integer NULL,
 "cd_passagem_wpd" varchar(10) NULL,
 "data_entrada"    timestamp NULL,
 "hora_entrada"    timestamp NULL,
 "data_saida"      timestamp NULL,
 "hora_saida"      timestamp NULL,
 "tipo_paciente"   varchar(50) NULL,
 "especialidade"   varchar(100) NULL,
 CONSTRAINT "idx_id_prontuario" FOREIGN KEY ( "id_prontuario" ) REFERENCES "public"."mec_prontuario" ( "id_prontuario" ) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE UNIQUE INDEX "PK_id_passagem" ON "public"."mec_passagem"
(
 "id_passagem"
);

CREATE INDEX "FK_id_prontuario" ON "public"."mec_passagem"
(
 "id_prontuario"
);

CREATE INDEX "idx_cd_passagem_wpd" ON "public"."mec_passagem"
(
 "cd_passagem_wpd"
);













-- *************** SqlDBM: PostgreSQL ****************;
-- ***************************************************;


-- ************************************** "public"."mec_leito"

CREATE TABLE "public"."mec_leito"
(
 "id_leito"        integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 "data_inclusao"   timestamp NULL,
 "data_alteracao"  timestamp NULL,
 "id_passagem"     integer NULL,
 "id_reg"          varchar(10) NULL,
 "leito"           varchar(25) NULL,
 "cd_passagem_wpd" varchar(10) NULL,
 CONSTRAINT "idx_id_passagem" FOREIGN KEY ( "id_passagem" ) REFERENCES "public"."mec_passagem" ( "id_passagem" ) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE UNIQUE INDEX "PK_id_leito" ON "public"."mec_leito"
(
 "id_leito"
);

CREATE INDEX "FK_id_passagem" ON "public"."mec_leito"
(
 "id_passagem"
);

CREATE INDEX "idx_id_reg" ON "public"."mec_leito"
(
 "id_reg"
);